options:
    admin_secret:
        type: string
        description: |
            The admin password used to talk to the Juju REST API to do bundle orchestration. You
            will not be able to use juju to deploy CF until this is properly set.
    cf_version:
        type: string
        desription: |
            The release of CF to switch the deployed bundle to.
    domain:
        type: string
        description: |
            The router domain, set to a xip.io address by default.
        default: xip.io
